### ISSUE TITLE
Call to a member function createIndexTable() on a non-object

### ISSUE THREAD

**Issue by danycrup85** [Vinai/groupscatalog2#111]
Hello,
I have this error when i try to reindex.

"PHP Fatal error:  Call to a member function createIndexTable() on a non-object in /Library/WebServer/Documents/magento18/www/app/code/community/Netzarbeiter/GroupsCatalog2/Model/Resource/Indexer/Abstract.php on line 187"

Where is the problem?

Thanks

**Comment by Vinai** [comment]
Thanks for your issue report.
Please check if the following file exists and is indeed a file (not a directory):
`/Library/WebServer/Documents/magento18/www/app/code/community/Netzarbeiter/GroupsCatalog2/Model/Resource/Setup.php`

If not, you can fetch it from this repository to create it:
https://raw.githubusercontent.com/Vinai/groupscatalog2/master/app/code/community/Netzarbeiter/GroupsCatalog2/Model/Resource/Setup.php

**Comment by danycrup85** [comment]
Thanks for the answer.
I see that the file Setup.php exists and is a file and not a directory.

![schermata 2015-01-16 alle 11 22 42](https://cloud.githubusercontent.com/assets/8995116/5774791/055f77d8-9d72-11e4-8321-39c1d8d584c3.png)
![schermata 2015-01-16 alle 11 21 04](https://cloud.githubusercontent.com/assets/8995116/5774794/0a72cd60-9d72-11e4-97a3-adee79b894f4.png)

**Comment by Vinai** [comment]
Please check if the latest version fixes the issue for you.

**Comment by danycrup85** [comment]
Ok, now it works. Thanks
For you, it is difficult to make a change in the extension that gives different permissions on every single product?

**Comment by Vinai** [comment]
Setting visibility on a product level is possible out of the box with this extension. So either you have missed that part of the functionality, or I am misunderstanding you.
