### ISSUE TITLE
Will this be available for Magento 2?

### ISSUE THREAD

**Issue by tomispepe** [Vinai/groupscatalog2#122]
If not, why not.  If so, will you share a rough timeline?  

Thank you!

**Comment by Vinai** [comment]
Thanks for your question. The answer is maybe.  
If I have need during a project I'll port (or maybe re-implement) the extension for Magento 2.
If not probably not. I would like to simply port it and support it just for fun, but unfortunately I have to choose where I spend the time I have.
So please don't hold your breath, it might be years. It really depends.
