### ISSUE TITLE
Index Management Issue

### ISSUE THREAD

**Issue by riev** [Vinai/groupscatalog2#123]
Hi, I'm having a bit of trouble with the Groups Catalog 2 and wonder if you can help.

I have Magento V 1.9.2.1 running with just the Groups Catalog 2 extension installed.

My Catalog Search Index is Red requires a Reindex, but each time it gives me an error "Cannot initialize the indexer process."

And also each time I make a new product and add it to a category, it doesn't show until I have Reindexed the Category Products Index, even though the Category Products Index shows as Green and Ready.

Thanks

**Comment by Vinai** [comment]
Please check the files `var/log/exception.log` and `var/log/system.log` for more information.
The message you posted is just the generic message displayed on the backend. Usually a more detailed message is written to the logs.

**Comment by riev** [comment]
Thanks Vinai, it was because my table had become corrupted and that was what was causing the issue.

I'm new to Magento and didn't realise that it doesn't log errors automatically, so I wasn't sure what was going on. Sorry to have wasted your time when I could have figured it out myself.

**Comment by Vinai** [comment]
No problem, glad you figured it out!
