### ISSUE TITLE
How to set groupscatalog2_groups programmatically

### ISSUE THREAD

**Issue by DocOlson** [Vinai/groupscatalog2#129]
Hello,

I am coding a custom importer with models. I am wondering how to set the values via code.
I tried setting groupscatalog2_groups as an array with the groups' ids in a product's data array. But that did not work.

Could someone please point me in the right direction?

Thank you

**Comment by DocOlson** [comment]
Nobody an idea?

**Comment by pquerner** [comment]
When creating/updating a category via AvS' fast-simple-importer you must give the value for 'groupscatalog2_groups' as string.

So I'm thinking its just about the same for products, then?

**Comment by DocOlson** [comment]
Yes, it is using a comma separated string. Intuitively i expected an array to be passed. Took me a while to figure out.
