### ISSUE TITLE
Error with a configurable product in the cart.

### ISSUE THREAD

**Issue by diwakert** [Vinai/groupscatalog2#140]
Hi Vinai,

I was trying out your extension for my project where client had similar requirements which this extension seems to address nicely. However, while testing I got stuck with an issue. 

I did check the list of issues for similar reported issues but haven't found any. Hope that you can point me in the right direction. 

It seems to be with configurable product types. Test case is below:

- Add an configurable product to cart.
- While the product is in the cart, hide the product from current customer group(_First I hide the child item and then tried with parent item itself_).
- Cart page breaks instead of product getting removed automatically I guess.

Attached is the first stack trace of the broken cart page.
![issue_configurable_item_in_cart](https://cloud.githubusercontent.com/assets/10129585/19477802/83ee67dc-955d-11e6-9f74-b40250aa25bf.png)

This second attached stack trace got generated when I tried to revert back the Hide from Groups setting to DEFAULT as cart page was fine before I hide the product from current customer group. But cart remained broken.
 
![issue_with_products_customer_group](https://cloud.githubusercontent.com/assets/10129585/19477546/55dc35dc-955c-11e6-8ef3-b56fc0746057.png)

**Comment by diwakert** [comment]
**Update:**
It was due another extension. The code was stuck calling collectTotals function on quote object in a loop.
Thanks for the great extension!

**Comment by Vinai** [comment]
Thanks for the update!
