### ISSUE TITLE
When HIDE_GROUPS_ATTRIBUTE isn't set, should fall back to USE_DEFAULT instead

### ISSUE THREAD

**Issue by kiatng** [Vinai/groupscatalog2#151]
I just installed _groupscatalog2_ in an existing CE 1.9.x. In the System Configuration, _Hide Categories from_ is set to **[NONE]**, which is `netzarbeiter_groupscatalog2/general/category_default_hide = -1` in the table _core_config_data_.  The existing categories have the attribute HIDE_GROUPS_ATTRIBUTE like this:

![image](https://user-images.githubusercontent.com/1106470/45015154-664e9400-b053-11e8-868e-fb1a786d3124.png)

However, all categories are hidden when _groupscatalog2_ is enabled. To show the categories, I need to save each category to set the attribute HIDE_GROUPS_ATTRIBUTE to [USE DEFAULT] with value -2. I expect that when HIDE_GROUPS_ATTRIBUTE isn't set, it should fall back to USE_DEFAULT instead.

I fixed with the following in `Netzarbeiter_GroupsCatalog2_Helper_Data`

    //kiat: fixed bug: when the entity's attribute isn't set, fall back on [USE DEFAULT]
    if ($groupIds === null) {
        $groupIds = array(self::USE_DEFAULT);
    } elseif (!is_array($groupIds) && !is_string($groupIds)) {
        // If the value isn't set on the entity mode fall back to querying the db index table
        $visibility = Mage::getResourceSingleton('netzarbeiter_groupscatalog2/filter')
                ->isEntityVisible($entity, $customerGroupId);
        $entity->setData(self::HIDE_GROUPS_ATTRIBUTE_STATE_CACHE, $visibility);
        return $visibility;
    }

In the above, the existing code `elseif` will always be false since when `$groupIds` is not null, it is either of type string or array. 

In the original code, if the category was saved so that `$groupIds` is not null, `elseif` will always be false. The `elseif` is true only when HIDE_GROUPS_ATTRIBUTE isn't set, but in this case, `$visibility` is always false because the _group_id_ column in both idx tables cannot hold the value -2 [USE DEFAULT]. Hence, I think this is a bug.

**Comment by Vinai** [comment]
Hi @kiatng, thanks for opening the issue. I haven't worked with the module in many years and don't support it any more, but if you want to submit a PR I'd be happy to merge it. If you can reproduce the issue in a test case before you fix it it would be even better 👍

**Comment by kiatng** [comment]
Hi @Vinai Thanks for the great extension. The earlier ver has been working great all these years. Today, I  installed ver 2 in another project, and deployed to production and that's when complaints started coming my way. I made a patch and deployed it. No complaint so far. So I made my very first PR.
